// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (parent_id, text)
VALUES ($1, $2)
RETURNING id, parent_id, text, created_at, updated_at
`

type CreateCommentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Text     string      `json:"text"`
}

type CreateCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.ParentID, arg.Text)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentSubtreeAsc = `-- name: GetCommentSubtreeAsc :many
WITH RECURSIVE comment_tree AS (
    SELECT
        c.id, c.parent_id, c.text, c.created_at, c.updated_at,
        ARRAY[c.created_at] AS sort_path
    FROM comments c
    WHERE c.id = $1

    UNION ALL

    SELECT
        c.id, c.parent_id, c.text, c.created_at, c.updated_at,
        ct.sort_path || c.created_at
    FROM comments c
             JOIN comment_tree ct ON c.parent_id = ct.id
)
SELECT id, parent_id, text, created_at, updated_at FROM comment_tree
ORDER BY sort_path
`

type GetCommentSubtreeAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommentSubtreeAsc(ctx context.Context, rootID pgtype.UUID) ([]GetCommentSubtreeAscRow, error) {
	rows, err := q.db.Query(ctx, getCommentSubtreeAsc, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentSubtreeAscRow
	for rows.Next() {
		var i GetCommentSubtreeAscRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentSubtreeDesc = `-- name: GetCommentSubtreeDesc :many
WITH RECURSIVE comment_tree AS (
    SELECT
        c.id, c.parent_id, c.text, c.created_at, c.updated_at,
        ARRAY[EXTRACT(EPOCH FROM c.created_at) * -1] AS sort_path
    FROM comments c
    WHERE c.id = $1

    UNION ALL

    SELECT
        c.id, c.parent_id, c.text, c.created_at, c.updated_at,
        ct.sort_path || (EXTRACT(EPOCH FROM c.created_at) * -1)
    FROM comments c
             JOIN comment_tree ct ON c.parent_id = ct.id
)
SELECT id, parent_id, text, created_at, updated_at FROM comment_tree
ORDER BY sort_path
`

type GetCommentSubtreeDescRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommentSubtreeDesc(ctx context.Context, rootID pgtype.UUID) ([]GetCommentSubtreeDescRow, error) {
	rows, err := q.db.Query(ctx, getCommentSubtreeDesc, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentSubtreeDescRow
	for rows.Next() {
		var i GetCommentSubtreeDescRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootCommentsAsc = `-- name: GetRootCommentsAsc :many
SELECT id, parent_id, text, created_at, updated_at
FROM comments
WHERE parent_id is NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $1
`

type GetRootCommentsAscParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

type GetRootCommentsAscRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRootCommentsAsc(ctx context.Context, arg GetRootCommentsAscParams) ([]GetRootCommentsAscRow, error) {
	rows, err := q.db.Query(ctx, getRootCommentsAsc, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRootCommentsAscRow
	for rows.Next() {
		var i GetRootCommentsAscRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootCommentsDesc = `-- name: GetRootCommentsDesc :many
SELECT id, parent_id, text, created_at, updated_at
FROM comments
WHERE parent_id is NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type GetRootCommentsDescParams struct {
	Offset int32 `json:"offset_"`
	Limit  int32 `json:"limit_"`
}

type GetRootCommentsDescRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRootCommentsDesc(ctx context.Context, arg GetRootCommentsDescParams) ([]GetRootCommentsDescRow, error) {
	rows, err := q.db.Query(ctx, getRootCommentsDesc, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRootCommentsDescRow
	for rows.Next() {
		var i GetRootCommentsDescRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchComments = `-- name: SearchComments :many
SELECT id, parent_id, text, created_at, updated_at
FROM comments
WHERE tsv @@ to_tsquery('russian', $1)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type SearchCommentsParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset_"`
	Limit  int32  `json:"limit_"`
}

type SearchCommentsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchComments(ctx context.Context, arg SearchCommentsParams) ([]SearchCommentsRow, error) {
	rows, err := q.db.Query(ctx, searchComments, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCommentsRow
	for rows.Next() {
		var i SearchCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :one
UPDATE comments
SET text = '[deleted]', updated_at = NOW(), tsv = NULL
WHERE id = $1
RETURNING id, parent_id, text, created_at, updated_at
`

type SoftDeleteCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Text      string             `json:"text"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SoftDeleteComment(ctx context.Context, id pgtype.UUID) (SoftDeleteCommentRow, error) {
	row := q.db.QueryRow(ctx, softDeleteComment, id)
	var i SoftDeleteCommentRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
