// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	GetCommentSubtreeAsc(ctx context.Context, rootID pgtype.UUID) ([]GetCommentSubtreeAscRow, error)
	GetCommentSubtreeDesc(ctx context.Context, rootID pgtype.UUID) ([]GetCommentSubtreeDescRow, error)
	GetRootCommentsAsc(ctx context.Context, arg GetRootCommentsAscParams) ([]Comment, error)
	GetRootCommentsDesc(ctx context.Context, arg GetRootCommentsDescParams) ([]Comment, error)
	SearchComments(ctx context.Context, arg SearchCommentsParams) ([]Comment, error)
	SoftDeleteComment(ctx context.Context, id pgtype.UUID) (Comment, error)
}

var _ Querier = (*Queries)(nil)
